// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: gRPC/v1/authenticate/challengeid/challengeid.proto

package challengeid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescGZIP(), []int{0}
}

type GetChallengeIdPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eula        string `protobuf:"bytes,1,opt,name=Eula,proto3" json:"Eula,omitempty"`
	ChallengeId string `protobuf:"bytes,2,opt,name=ChallengeId,proto3" json:"ChallengeId,omitempty"`
}

func (x *GetChallengeIdPayload) Reset() {
	*x = GetChallengeIdPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChallengeIdPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeIdPayload) ProtoMessage() {}

func (x *GetChallengeIdPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeIdPayload.ProtoReflect.Descriptor instead.
func (*GetChallengeIdPayload) Descriptor() ([]byte, []int) {
	return file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescGZIP(), []int{1}
}

func (x *GetChallengeIdPayload) GetEula() string {
	if x != nil {
		return x.Eula
	}
	return ""
}

func (x *GetChallengeIdPayload) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

var File_gRPC_v1_authenticate_challengeid_challengeid_proto protoreflect.FileDescriptor

var file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x69, 0x64, 0x2f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x69, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x69,
	0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4d, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x64, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x45, 0x75, 0x6c, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x45, 0x75, 0x6c, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x64, 0x32, 0x5e, 0x0a, 0x12, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x69, 0x64, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x69, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x49, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x65, 0x4c, 0x61, 0x7a, 0x61, 0x72,
	0x75, 0x73, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x69, 0x64, 0x3b, 0x63, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescOnce sync.Once
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescData = file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDesc
)

func file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescGZIP() []byte {
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescOnce.Do(func() {
		file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescData)
	})
	return file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDescData
}

var file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_v1_authenticate_challengeid_challengeid_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: challengeid.Empty
	(*GetChallengeIdPayload)(nil), // 1: challengeid.GetChallengeIdPayload
}
var file_gRPC_v1_authenticate_challengeid_challengeid_proto_depIdxs = []int32{
	0, // 0: challengeid.challengeidService.GetChallengeId:input_type -> challengeid.Empty
	1, // 1: challengeid.challengeidService.GetChallengeId:output_type -> challengeid.GetChallengeIdPayload
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_v1_authenticate_challengeid_challengeid_proto_init() }
func file_gRPC_v1_authenticate_challengeid_challengeid_proto_init() {
	if File_gRPC_v1_authenticate_challengeid_challengeid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChallengeIdPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_v1_authenticate_challengeid_challengeid_proto_goTypes,
		DependencyIndexes: file_gRPC_v1_authenticate_challengeid_challengeid_proto_depIdxs,
		MessageInfos:      file_gRPC_v1_authenticate_challengeid_challengeid_proto_msgTypes,
	}.Build()
	File_gRPC_v1_authenticate_challengeid_challengeid_proto = out.File
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_rawDesc = nil
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_goTypes = nil
	file_gRPC_v1_authenticate_challengeid_challengeid_proto_depIdxs = nil
}
